# Generated by Django 5.2.1 on 2025-07-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='teléfono',
            new_name='telefono',
        ),
    ]
