# Generated by Django 5.2.1 on 2025-07-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_rename_teléfono_restaurante_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='restaurante',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
