# Generated by Django 5.2.1 on 2025-07-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_rename_descripción_menu_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartidor',
            old_name='teléfono',
            new_name='telefono',
        ),
    ]
