# Generated by Django 5.2.1 on 2025-07-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_rename_teléfono_repartidor_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='direccion',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repartidor',
            name='edad',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
    ]
